name: Deploy to EKS

on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426043895157:role/plane-github-actions-eks-role-dev
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name plane-eks-dev

      - name: Verify access
        run: |
          kubectl get nodes

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::426043895157:role/plane-github-actions-secrets-role-dev
          aws-region: us-east-1

      - name: Retrieve deploy secrets from AWS Secrets Manager
        id: deploy-secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_NAME || 'github-actions/github-actions-secrets' }} --query SecretString --output text)
          CLOUDFLARE_TOKEN=$(echo $SECRET_JSON | jq -r '.cloudflare_api_token')
          echo "cloudflare_token=$CLOUDFLARE_TOKEN" >> $GITHUB_ENV
          echo "::add-mask::$CLOUDFLARE_TOKEN"          
